### PR TITLE
Adding pagination (first version)

### PR DESCRIPTION
**Pull request by marcosmercuri**
Addressing this [issue](https://github.com/SteffiPeTaffy/conference-rating/issues/49)

I split the `conference` endpoint into two (one for past conferences, and one for future), as the pagination is independent from one another. I didn't remove the original, as I think it could be used for the searchbox search.

This is a first version. I plan to add a few more improvements:
- ~~Order the conferences by date when querying the database (so the ones closer to today appear in the first pages)~~
- Improve the search box (right now it only searches in the conferences being displayed)
- ~~Get the number of pages, so you can't go to the next page if there aren't any~~
- ~~Improve the UX when switching between pages (now it feels kind of weird)~~
- Review the code and see what can be improved

I'd appreciate any feedback in general, and on things that could make the code more idiomatic to Clojure.

### CODE REVIEW

**Comment by flosell** [comment]
Hi @marcosmercuri, 

sorry for taking a while to have a look. 
Thanks for this feature! Looking good overall. 
I think you are right, the UX can be improved a bit. For example, I'm not sure if paging upcoming and past conferences independently feels good to me). Maybe we could even put the past conferences on a separate page in the future. All in all though, might be good enough as a first shot, I'll leave it up to you, let me know if you want me to merge and deploy in this state or if you want to add more improvements first. 

A few smaller things I noticed: 
* The "next page" button isn't disabled when there are no more pages in the future, so you'll eventually end up with an empty page. Feels a bit weird. 
* What's the `style.txt` file? is it necessary or accidentally commmitted?

**Comment by marcosmercuri** [comment]
Hi, @flosell ,
Thanks for the feedback, and don't worry about the delay :)

The split of past and future conferences is an interesting discussion. I thought of splitting them for the pagination, as I thought it was going to be weird that, for example, in the first page you have no past conferences, but in the second one you do.
I also thought of putting the past conferences in separate page, but I thought of it as a later step (first deploying this first approach)

Regarding the things you noticed:

- Yes, that's one of the things in the list to fix. I actually have it almost ready. 
- You are right, that was accidentally committed. I'll remove it.

I'd say, give me a few more days to finish the disable of the "next button", and I think we can merge it. I'll let you know when I have it done.
Thanks

**Comment by marcosmercuri** [comment]
Hi, @flosell,
I've just pushed the changes to disable the "next page" button if there are no more conferences.
If you feel is good enough, you can merge it.
Thanks

**Comment by flosell** [comment]
Hi, thank you for that! I think it's good enough to merge. 

Here are a few things I noticed while looking at the code again, if you have some free time might be worth a second look and PR: 
* the `per-page` API parameter isn't really necessary, is it? yet it opens the API quite wide so for a large number of items, if I'm a malicious user, I can put a lot of load on the DB by just calling the API with a large per-page number
* there seem to be quite a few almost-duplications in the code to distinguish between past and future conferences. Not too bad but doesn't feel too elegant :) 
* `get-count-future-conferences` - I'd probably just name it `count-future-conferences`, easier to read :)

**Comment by flosell** [comment]
Ah, and one more thing I just realised: There's a separate server listening on port 4000 during functional tests, use that instead of the development server to ensure that functional tests can run without the development server running. I've fixed that in d7163248b376880095acf7ec1921858d23626888

**Pull request merged**
